### ISSUE TITLE
Type definitions break when there is more than one generic

### ISSUE THREAD

**Issue by anthony0br** [evaera/moonwave#151]
The following code results in an unexpected output in `moonwave dev`

```luau
--[=[
	@type Result<T, E> Ok<T> | Err<E>

	The result of a yielding operation that could error. You should always write
	error handling for all types of errors that can be returned.
	
	@within DocumentService
]=]
export type Result<T, E> = Ok<T> | Err<E>
```
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/ba960d93-3b80-4395-acbc-5b1762063c72">

This happens with any type which uses multiple generics.

In `moonwave build`, it will always fail. For my project, I get this stack trace (on macos):
```
[ERROR] Minification of page /api/DocumentService failed.
[ERROR] Docusaurus server-side rendering could not render static page with path /api/DocumentService.


Error: Parse Error: <T,</a></li><li><a href="#RobloxAPIError" class="table-of-contents__link toc-highlight">RobloxAPIError</a></li><li><a href="#SessionLockedError" class="table-of-contents__link toc-highlight">SessionLockedError</a></li><li><a href="#Transform&lt;T&gt;" class="table-of-contents__link toc-highlight">Transform<T></a></li></ul></li><li><a href="#properties" class="table-of-contents__link toc-highlight">Properties</a></li><li><a href="#functions" class="table-of-contents__link toc-highlight">Functions</a></li></ul></div></div></div></div></main></div></div><footer class="footer footer--dark"><div class="container container-fluid"><div class="footer__bottom text--center"><div class="footer__copyright">Copyright © 2024 anthony0br. Built with Moonwave and Docusaurus.</div></div></div></footer></div>
<script src="/DocumentService/assets/js/runtime~main.42f101ef.js"></script>
<script src="/DocumentService/assets/js/main.9dc2abd8.js"></script>
</body>
</html>
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Users/USER/Library/Caches/moonwave/DocumentService/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /Users/USER/Library/Caches/moonwave/DocumentService/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/USER/Library/Caches/moonwave/DocumentService/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[INFO] Docusaurus version: 2.3.1
Node version: v22.5.1
Error: Build had an non-zero exit code
Moonwave: It looks like something went wrong. Check the error output above.
```

**Comment by anthony0br** [comment]
As a workaround, I am writing @type Result Ok<T> | Err<E>

**Comment by YetAnotherClown** [comment]
Using the generic type syntax in doc entry names isn't supported by Moonwave currently, there are several issues with it.

#### Firstly, the issue you're running into here:

Moonwave parses `@type Result<T, E> Ok<T> | Err<E>` as:
- name: `Result<T,`
- type: `E> Ok<T> | Err<E>`

#### And other issues:

- Breaks hyperlinks to those doc entries
- Classes with generics in their name are not properly routed to

And I am sure there may be some other issues.

This is however something that is commonly used among strict typing users, and something that would be nice to support before the new type solver is released for beta use.

**Comment by anthony0br** [comment]
Thanks! I've also checked and as you mentioned on Discord `@type Result<T,E> Ok<T> | Err<E>` (without the space) is parsed correctly, so I'll close this.
